import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./themeProvider/page";
import { Kanit } from "next/font/google";
import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });
const kanit = Kanit({ weight: "300", subsets: ['thai']});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kanit.className} bg-[#f5f5f5] dark:bg-[#000]`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main>{children}</main>
        </ThemeProvider>
        <Script src="../path/to/flowbite/dist/flowbite.min.js" />
      </body>
    </html>
  );
}
